paths:
  /api/products/products:
    get:
      tags:
        - Products
      summary: Get all products
      description: Get all products
      operationId: getProducts
      produces:
        - application/json
      responses:
        "200":
          description: All Products
        "404":
          description: Products Not Found
        "500":
          description: Internal Server Error
    post:
      tags:
        - Products
      summary: Create a product
      description: Create a product
      operationId: createProduct
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Product object that needs to be added
          required: true
          schema:
            $ref: "#/components/schemas/Product"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
              example:
                id: 1
                name: "Product 1"
                description: "Product 1 description"
                price: 100
                quantity: 10
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
    /api/products/products{id}:
      get:
        tags:
          - Products
        summary: Get a product by id
        description: Get a product by id
        operationId: getProductById
        produces:
          - application/json
        parameters:
          - name: id
            in: path
            description: ID of product to return
            required: true
            type: integer
            format: int64
        responses:
          "200":
            description: Product
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Product"
                example:
                  id: 1
                  name: "Product 1"
                  description: "Product 1 description"
                  price: 100
                  quantity: 10
          "404":
            description: Product Not Found
          "500":
            description: Internal Server Error
      put:
        tags:
          - Products
        summary: Update a product
        description: Update a product
        operationId: updateProduct
        consumes:
          - application/json
        produces:
          - application/json
        parameters:
          - name: id
            in: path
            description: ID of product to return
            required: true
            type: integer
            format: int64
          - in: body
            name: body
            description: Product object that needs to be updated
            required: true
            schema:
              $ref: "#/components/schemas/Product"
        responses:
          "200":
            description: Product
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Product"
                example:
                  id: 1
                  name: "Product 1"
                  description: "Product 1 description"
                  price: 100
                  quantity: 10
          "400":
            description: Bad Request
          "401":
            description: Unauthorized
          "403":
            description: Forbidden
          "404":
            description: Not Found
          "500":
            description: Internal Server Error
      delete:
        tags:
          - Products
        summary: Delete a product
        description: Delete a product
        operationId: deleteProduct
        produces:
          - application/json
        parameters:
          - name: id
            in: path
            description: ID of product to return
            required: true
            type: integer
            format: int64
        responses:
          "200":
            description: Product
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Product"
                example:
                  id: 1
                  name: "Product 1"
                  description: "Product 1 description"
                  price: 100
                  quantity: 10
          "400":
            description: Bad Request
          "401":
            description: Unauthorized
          "403":
            description: Forbidden
          "404":
            description: Not Found
          "500":
            description: Internal Server Error
